version: '3.4'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     container_name: chpro-db
     environment:
       MYSQL_DATABASE: superset
       MYSQL_USER: superset
     secrets:
       - CHPRO_MYSQL_ROOT_PASSWORD
       - CHPRO_MYSQL_PASSWORD
     deploy:
       restart_policy:
         condition: on-failure
   chpro:
     depends_on:
       - db
     build: .
     image: chpro:latest
     ports:
       - "9090:9090"
     restart: always
     container_name: chpro-app
     secrets:
       - CHPRO_MYSQL_ROOT_PASSWORD
       - CHPRO_MYSQL_PASSWORD
     deploy:
       restart_policy:
         condition: on-failure

volumes:
    db_data:

secrets:
  CHPRO_MYSQL_ROOT_PASSWORD:
    external: true
  CHPRO_MYSQL_PASSWORD:
    external: true
