version: '3.4'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     container_name: chpro-db
     environment:
       MYSQL_DATABASE: superset
       MYSQL_USER: superset
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD
       MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
     volumes:  # Manually mounting the secrets
       - ./secrets:/run/secrets
   chpro:
     depends_on:
       - db
     build:
      context: .
      dockerfile: ./ops/containers/app/Dockerfile
     image: chpro:latest
     restart: always
     ports:
       - "9090:9090"
     container_name: chpro-app
     volumes:  # Manually mounting the secrets
       - ./secrets:/run/secrets
volumes:
    db_data:
