version: '3.4'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_DATABASE: superset
       MYSQL_USER: superset
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD
       MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
     secrets:
       - MYSQL_ROOT_PASSWORD
       - MYSQL_PASSWORD
     deploy:
       restart_policy:
         condition: on-failure

   chpro:
     depends_on:
       - db
     image: chpro:production
     ports:
       - "9090:9090"
     secrets:
       - MYSQL_ROOT_PASSWORD
       - MYSQL_PASSWORD
       - RAPIDPRO_API_KEY
       - DOCS_USER
       - DOCS_PASSWORD
     deploy:
       replicas: 2
       restart_policy:
         condition: on-failure

volumes:
    db_data:

secrets:
  MYSQL_ROOT_PASSWORD:
    external: true
  MYSQL_PASSWORD:
    external: true
  RAPIDPRO_API_KEY:
    external: true
  DOCS_USER:
    external: true
  DOCS_PASSWORD:
    external: true
